version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/nexus.db:/app/nexus.db
    environment:
      - JWT_SECRET=NEXUS_DC1_SUPER_SECRET_KEY_PROD_123

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
